services:
  nginx:
    container_name: nginx_container
    restart: unless-stopped
    image: nginx:alpine
    volumes:
      - ../../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - session_confs:/etc/nginx/sessions
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

  backend:
    container_name: backend_container
    restart: unless-stopped
    build:
      context: ../../backend
      dockerfile: Dockerfile.development
    volumes:
      - ../../backend:/app
      - /tmp/sessions:/tmp/sessions
      - /var/run/docker.sock:/var/run/docker.sock
      - session_confs:/etc/nginx/sessions
    env_file:
      - ../../.env.development
    ports:
      - "8000:7000"
    environment:
      - SESSIONS_DIR=/tmp/sessions
      - NGINX_SESSIONS_DIR=/etc/nginx/sessions

  frontend:
    container_name: frontend_container
    restart: unless-stopped
    build:
      context: ../../frontend
      dockerfile: Dockerfile.development
    volumes:
      - ../../frontend/src:/usr/src/app/src
    expose:
      - "5173"
    ports:
      - "5173:5173"

  redis:
    container_name: redis_container
    restart: unless-stopped
    image: redis:8
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  mongodb:
    container_name: mongodb_container
    restart: unless-stopped
    image: mongo:8
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: llm-code
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
  redis-data:
  session_confs:
