services:
  backend:
    container_name: backend_container
    restart: unless-stopped
    build:
      context: ../../backend
      dockerfile: Dockerfile
    volumes:
      - ../../backend:/app
    env_file:
      - ../../.env.development

  frontend:
    container_name: frontend_container
    restart: unless-stopped
    build:
      context: ../../frontend
      dockerfile: Dockerfile.development
    volumes:
      - ../../frontend/src:/usr/src/app/src
    ports:
      - "5173:5173"

  redis:
    container_name: redis_container 
    restart: unless-stopped
    image: redis:8
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  postgres:
    container_name: postgres_container
    restart: unless-stopped
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: llm-code
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  redis-data:
